### ISSUE TITLE
Usar Java.Util.Date ao invés de java.util.Calendar

### ISSUE THREAD

**Issue by rmdantas** [Benezes/webapp#1]
É aconselhável utilizar `Java.Util.Date` para entidades e `java.time.LocalDate` quando for manipular datas.

https://github.com/Benezes/webapp/blob/13d05bb1ea723d290842c96587e46f533798db14/src/main/java/box/modelo/Contato.java#L17

https://github.com/Benezes/webapp/blob/13d05bb1ea723d290842c96587e46f533798db14/src/main/java/box/dao/ContatoDao.java#L31

Não será necessário ficar instanciando um novo objeto `Java.Util.Date`, basta dar um `contato.getDataNascimento()`

**Comment by Benezes** [comment]
all fidex
Duplicate of #1
